# Generated by Django 4.0.7 on 2025-04-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('phone_number', models.PositiveBigIntegerField()),
                ('employee_module', models.CharField(max_length=100)),
                ('approve', models.BooleanField(default=0, null=True)),
                ('reject', models.BooleanField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Br_id', models.CharField(max_length=200, null=True)),
                ('Building_type', models.CharField(max_length=100)),
                ('number_of_rooms', models.IntegerField()),
                ('area', models.FloatField()),
                ('water_body', models.CharField(max_length=100)),
                ('distance_to_water_body_m', models.FloatField()),
                ('water_body_temperature', models.FloatField()),
                ('temperature', models.FloatField(null=True)),
                ('building_material', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('material', models.CharField(max_length=100, null=True)),
                ('diameter_mm', models.FloatField(null=True)),
                ('length_m', models.FloatField(null=True)),
                ('insulation_type', models.CharField(max_length=100, null=True)),
                ('insulation_thickness_mm', models.FloatField(null=True)),
                ('pressure_rating_pa', models.FloatField(null=True)),
                ('heat_transfer_coefficient_w_m2k', models.FloatField(null=True)),
                ('ptdone', models.BooleanField(default=False, null=True)),
                ('hedone', models.BooleanField(default=False, null=True)),
                ('bidone', models.BooleanField(default=False, null=True)),
                ('htdone', models.BooleanField(default=False, null=True)),
                ('fview', models.BooleanField(default=False, null=True)),
                ('Q_primary', models.FloatField(null=True)),
                ('Q_secondary', models.FloatField(null=True)),
                ('brine_solution', models.CharField(max_length=100, null=True)),
                ('HTC', models.FloatField(null=True)),
                ('Thermal_Conductivity', models.FloatField(null=True)),
                ('Density', models.FloatField(null=True)),
                ('final_temperature', models.FloatField(null=True)),
                ('f_report', models.FileField(blank=True, null=True, upload_to='pdf_reports/')),
            ],
        ),
    ]
